package ar.edu.unlu.zombi.modelo.enumerados;

public enum EventoJugador {
	ERROR_LIMITE_MINIMO_JUGADORES,
	ERROR_LIMITE_MAXIMO_JUGADORES,
	MOSTRAR_PANTALLA_CARGA_NOMBRE_JUGADOR,
	ERROR_VALIDACION_NOMBRE_JUGADOR,
	MOSTRAR_PANTALLA_ESPERA_JUGADORES,
	EVENTO_GLOBAL,
	ERROR_REMOTE_EXCEPTION
}
